const express = require('express');
const serverless = require('serverless-http');
const cors = require('cors');
require('dotenv').config();
const apiRoutes = require('./routes/blogs');
const passport = require("passport");
const app = express();
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use(passport.initialize());
require("./config/passport")(passport);
app.use('/', apiRoutes);
// const server = require('http').createServer(app);
// server.listen(process.env.PORT, () => console.log("Server is starting on blogs "));
module.exports.handler = serverless(app);
