name: Build
on:
  push:
    branches:
      - develop
 
jobs:
  sonarqube:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java [required by SonarScanner]
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: /home/runner/work/Rentte-backend/Rentte-backend/Rentte/Rentte-aws-lambda
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sudo npm install
          sudo npm install moment-timezone knex aws-sdk jsonwebtoken winston aws-sdk-mock pg dotenv sharp node-input-validator axios crypto-js nodemailer @aws-sdk/client-s3
          export NODE_ENV=development
          sudo npm install --save-dev jest

      - name: Add Jest Script in package.json
        working-directory: /home/runner/work/Rentte-backend/Rentte-backend/Rentte/Rentte-aws-lambda
        run: |
          npm pkg set scripts.test="jest --coverage"

      - name: Create sonar-project.properties
        working-directory: /home/runner/work/Rentte-backend/Rentte-backend/Rentte/Rentte-aws-lambda
        run: |
          echo "sonar.projectKey=Rentte_Rentte-backend" > sonar-project.properties
          echo "sonar.organization=rentte" >> sonar-project.properties
          echo "sonar.sources=lambda" >> sonar-project.properties
          echo "sonar.language=js" >> sonar-project.properties
          echo "sonar.tests=test" >> sonar-project.properties
          echo "sonar.exclusions=**/node_modules/**,**/*.spec.js,**/test/**,**/unit-test/**,**/integration-test/**,coverage/**,bin/**,lib/**,**/routes/**,**/watermark/**,**/db/**/migrations/**,**/swagger_api/**,lambda/*/index.js,**/config/s3bucketConfig.js,**/swagger.js,**/config/memcached.js,**/config/passport.js" >> sonar-project.properties
          echo "sonar.javascript.lcov.reportPaths=coverage/lcov.info" >> sonar-project.properties
          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
          echo "sonar.eslint.reportPaths=eslint-report.json" >> sonar-project.properties
          echo "sonar.qualitygate.wait=true" >> sonar-project.properties
          echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
          
      - name: Create jest.config.js
        working-directory: /home/runner/work/Rentte-backend/Rentte-backend/Rentte/Rentte-aws-lambda
        run: |
          echo 'module.exports = {
              collectCoverage: true,
              collectCoverageFrom: [
                    "lambda/**/*.js",
                    "!**/node_modules/**",
                    "!**/test/**",
                    "!**/*.spec.js",
                    "!bin/**",
                    "!lib/**",
                    "!**/routes/**",
                    "!**/routes/**/*.js",
                    "!**/watermark/**",
                    "!**/watermark/**/*.js",
                    "!**/db/**/migrations/**",
                    "!**/swagger_api/**",
                    "!**/swagger_api/**/*.js",
                    "!lambda/*/index.js",
                    "!**/config/s3bucketConfig.js",
                    "!**/swagger.js",
                    "!**/config/memcached.js",     
                    "!**/config/passport.js",      
              ],
              coverageDirectory: "coverage",
              coverageReporters: ["lcov", "text-summary"],
              coveragePathIgnorePatterns: [
                  "/node_modules/",
                  "/test/",
                  "/unit-test/",
                  "/integration-test/",
                  "/bin/",
                  "/lib/",
                  "/routes/",
                  "/watermark/",
                  "/migrations/",
                  "/swagger_api/",
                  "lambda/.*/index\\.js$",
                  "config/s3bucketConfig\\.js$",
                  "swagger\\.js$",
                  "config/memcached\\.js$",
                  "config/passport\\.js$"
            ],
              testEnvironment: "node",
            };
            ' | sudo tee /home/runner/work/Rentte-backend/Rentte-backend/Rentte/Rentte-aws-lambda/jest.config.js > /dev/null

      - name: Run tests and generate coverage (example for Node.js)
        working-directory: /home/runner/work/Rentte-backend/Rentte-backend/Rentte/Rentte-aws-lambda
        run: |
          sudo npm run test -- --coverage
        continue-on-error: true    

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: /home/runner/work/Rentte-backend/Rentte-backend/Rentte/Rentte-aws-lambda
        env:
          SONAR_TOKEN: 955fc6516d674258e42e054ac1207105187650ed
          SONAR_PROJECT_KEY: Rentte_Rentte-backend
          SONAR_ORGANIZATION: rentte
        continue-on-error: true    
