name: "Validate Semantic PR"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - main  
jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            perf
            refactor
            style
            chore
            ci
            test
            build
            docs
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
